### ISSUE TITLE
Variables inside var blocks are duplicated

### ISSUE THREAD

**Issue by ccremer** [mariotoffia/goasciidoc#11]
Hi!
First of all this is an awesome project!

I noticed that in var blocks like
```go
var(
  ...
)
```
the variables are duplicated.

![image](https://user-images.githubusercontent.com/12159026/108620913-92327f80-742f-11eb-9e86-c667861c08d9.png)

**Comment by ccremer** [comment]
Ah, I was able to reconfigure the template. Instead of `.FullDecl`, I'm using just `.Decl`:
```
=== {{.VarAssignment.Name}}
[source, go]
----
{{.VarAssignment.Decl}}
----
{{.VarAssignment.Doc}}
```

**Comment by mariotoffia** [comment]
Thanks! @ccremer  :) - I'll add this as a bug! - It should be fixed in next release
https://github.com/mariotoffia/goasciidoc/blob/master/asciidoc/defaults.go#L130

Cheers,
 Mario :)

**Comment by mariotoffia** [comment]
@ccremer  I've changed the default to use `.Decl` instead.
