### ISSUE TITLE
not implemented: ArrayType

### ISSUE THREAD

**Issue by ccremer** [mariotoffia/goasciidoc#15]
Hi.
I'm getting an error with Arrays:
```go
type Color string
type Label struct {
	Name        string
	Description string
	color       Color
}
type LabelSet []Label
```
log:
```console
not-implemented typeSpec.Type.(type) = *ast.ArrayType, ast-dump:
----------------------
     0  *ast.ArrayType {
     1  .  Lbrack: domain/labelset.go:5:15
     2  .  Elt: *ast.Ident {
     3  .  .  NamePos: domain/labelset.go:5:17
     4  .  .  Name: "Label"
     5  .  }
     6  }
----------------------
```
I'm using latest version v0.4.5

The originating error seems to come from here:
https://github.com/mariotoffia/goasciidoc/blob/f5d25e784b2797d40a53acb62c3151c15d1eb596/goparser/internal_parser.go#L152-L163

Would be cool to have this also implemented 😄

**Comment by mariotoffia** [comment]
Hi @ccremer - Thanks for the bug report!!

I really like that you have outlined the code so I can write a unit test to reproduce it!

I'll have a look and hopefully a fix soon.

Cheers,
 Mario :)

**Comment by mariotoffia** [comment]
Hi @ccremer. I've done an update to support `ArrayType` - please have a [go](https://github.com/mariotoffia/goasciidoc/releases/tag/v0.4.6) and see so if it works for you?

Cheers,
 Mario :)

**Comment by ccremer** [comment]
It works! No more errors and the Array is there.
Thanks for the quick fix :)
Cheers
